name: Test / Validate Code

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Perform static analysis
        run: npm run lint

      - name: Check code format
        run: npm run format:check

      - name: Run unit tests
        run: npm run test
